name: PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: read
    uses: krypsis-io/.github/.github/workflows/dependency-review.yml@main
  trivy:
    permissions:
      contents: read
    uses: krypsis-io/.github/.github/workflows/trivy.yml@main
  semgrep:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: krypsis-io/.github/.github/workflows/semgrep.yml@main
